const gulp = require('gulp');
const batch = require('gulp-batch');
const watch = require('gulp-watch');
const electronMocha = require('gulp-electron-mocha').default;
const utils = require('./utils');

let runWatch = false;

gulp.task('test', () => {
	const config = {
		electronMocha: {
			renderer: true,
			compilers: 'js:babel-core/register',
			require: 'source-map-support/register',
			env: 'test',
		},
	};

	gulp.src('./app/specs.js.autogenerated', {
			read: false
		})
		.pipe(electronMocha(config))
		.on('error', function(error) {
			console.log(error);
		});

	if(!runWatch) {
		runWatch = true;
		gulp.start('watch-run-test', utils.beepOnError(function() {}));
		gulp.start('watch-build-test', utils.beepOnError(function() {}));
	}
});

gulp.task('watch-run-test', () => {
	watch('app/**/*.js', batch((events, done) => {
		delayTest();
		done();
	}));
});

let delayId = null;

function delayTest() {
	if(delayId !== null) {
		clearTimeout(delayId);
	}

	delayId = setTimeout(runTest, 1000);
}

function runTest() {
	delayId = null;
	gulp.start('test', utils.beepOnError(function(error) {
		if(error) {
			console.error(error);
		}
	}));
}
